version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/project'
      target-branch: 'Dev'
      open-pull-requests-limit: 18
      labels:
          - 'Dependabot'
          - 'Dependencies'
          - 'NodeJS'
      schedule:
          timezone: 'Europe/Berlin'
          interval: 'weekly'
          day: 'monday'
          time: '03:00'
